# Generated by Django 3.2.5 on 2021-07-11 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Names')),
                ('surnames', models.CharField(max_length=80, verbose_name='Surnames')),
                ('dni', models.CharField(max_length=11, unique=True, verbose_name='DNI')),
                ('date_birthday', models.DateField(default=datetime.datetime.now, verbose_name='Date birthday')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('todo', 'Todo lol')], default='todo', max_length=50, verbose_name='Gender')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Image')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('s_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=9, verbose_name='Selling price')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
