# Generated by Django 3.2.5 on 2021-07-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210713_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['id'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
