# Generated by Django 3.2.5 on 2021-09-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product description'),
        ),
    ]
