# Generated by Django 3.2.5 on 2021-09-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210929_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon </>'),
        ),
    ]
