# Generated by Django 3.2.5 on 2021-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_category_icon_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detsale',
            options={'ordering': ['id'], 'verbose_name': 'Sale detail', 'verbose_name_plural': 'Sales details'},
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('todo', 'Todo')], default='todo', max_length=50, verbose_name='Gender'),
        ),
    ]
