# Generated by Django 3.2.5 on 2021-10-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['owner', 'date_creation']},
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Low', max_length=22),
        ),
    ]
