# Generated by Django 3.2.5 on 2021-10-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211021_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_price',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=9, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_price',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=9, verbose_name='Selling price'),
        ),
    ]
