# Generated by Django 3.2.5 on 2021-10-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0004_alter_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
