# Generated by Django 3.2.5 on 2021-10-18 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0006_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_joined',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
