# Generated by Django 3.2.5 on 2021-10-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211019_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='carts_sent',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='products_added',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
